const Heroo = {

    firstName: "",
    lastName: "",
    gender: "", // [Male,Female,Other]
    age: "",
    education: "",
    martialStatus: "", //['Single','Married','Widower','Widow','Separated','Divorced']
    guardianName: "",
    language: "", //
    mobileNumber: "",
    eMail: "",
    address: "",
    medicineName: "",
    medicineDose: "",
    regularMedicine: "",
    brief: "",
    referenceFrom: "",
    oldStuName: "",
    firstCoursePlace: "",
    dateFirstCourse: "",
    dateLastCourse: "",
    firstAsstTeacher: "",
    lastCoursePlace: "",
    lastAsstTeacher: "",
    courseDetails: "",
    triedAnyPractise: "",
    practiseRegularly: "",
    dailyHours: "",
    reason: "",
    changeInYourSelf: "",
    personName: "",
    personRelation: "",
    courseDone: "",
    relation: "",
    designation: "",
    companyName: "",
    companyAddress: "",
    inPastOne: "",
    inPresentOne: "",
    FitnessCertificate: "",
    inPastTwo: "",
    inPresentTwo: ""
}
